[advisories]
db-path = "~/.cargo/advisory-db"
ignore = []
severity-threshold = "medium"

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC", "Unlicense"]
deny = []

[sources]
unknown-registry = "deny"
unknown-git      = "deny"
allow-registry   = ["https://github.com/rust-lang/crates.io-index"]
